stages:
  file_conv:
    cmd: jupyter nbconvert processing.ipynb --to python
    deps:
    - data
    - processing.ipynb
    outs:
    - processing.py
  model_conv:
    cmd: jupyter nbconvert model.ipynb --to python
    deps:
    - model.ipynb
    outs:
    - model.py
  make_csv:
    cmd: python processing.py
    deps:
    - processing.py
    outs:
    - csv_storage/test.csv
    - csv_storage/train.csv
    - csv_storage/valid.csv
